# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:macos)

platform :macos do
  desc "Description of what the lane does"
  lane :build do

    increment_build_number
    
    build_mac_app(
      output_directory: "./build",
      export_method: "developer-id"
    )
    
    # notarize(
      # package: "./build/AOS.app",
      # use_notarytool: true,
      # username: "hechen4815463@163.com"
    # )
  end
end
